/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.radd;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Piotr
 */
public class CoverFrame extends javax.swing.JFrame {

    /**
     * Creates new form CoverFrame
     */
    public CoverFrame(Image img) {
        initComponents();
        setCover(img);
        img = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coverIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());
        getContentPane().add(coverIcon);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel coverIcon;
    // End of variables declaration//GEN-END:variables

    private void setCover(Image img) {
        ImageIcon ii = new ImageIcon(img);
        coverIcon.setIcon(ii);
        img.flush();
        img = null;
        ii = null;
    }
}
