/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.radd;

/**
 *
 * @author Piotr
 */
public class FilePanel extends javax.swing.JPanel {

    /**
     * Creates new form FilePanel
     */
    public FilePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        artistText = new javax.swing.JTextField();
        albumText = new javax.swing.JTextField();
        titleText = new javax.swing.JTextField();
        yearText = new javax.swing.JTextField();
        genreText = new javax.swing.JTextField();
        title = new javax.swing.JTextField();
        fileNameText = new javax.swing.JTextField();
        urlText = new javax.swing.JTextField();
        filename = new javax.swing.JTextField();
        encoder = new javax.swing.JTextField();
        album = new javax.swing.JTextField();
        artist = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        genre = new javax.swing.JTextField();
        copyrightText = new javax.swing.JTextField();
        albumArtistText = new javax.swing.JTextField();
        originalArtistText = new javax.swing.JTextField();
        publisherText = new javax.swing.JTextField();
        encoderText = new javax.swing.JTextField();
        composerText6 = new javax.swing.JTextField();
        url = new javax.swing.JTextField();
        copyright = new javax.swing.JTextField();
        albumArtist = new javax.swing.JTextField();
        oroginalArtist = new javax.swing.JTextField();
        publisher = new javax.swing.JTextField();
        composer = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 15, 0, 15, 0};
        layout.rowHeights = new int[] {0, 11, 0, 11, 0, 11, 0, 11, 0, 11, 0, 11, 0, 11, 0, 11, 0, 11, 0, 11, 0, 11, 0, 11, 0};
        setLayout(layout);

        artistText.setEditable(false);
        artistText.setText("Artist:");
        artistText.setBorder(null);
        artistText.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(artistText, gridBagConstraints);

        albumText.setEditable(false);
        albumText.setText("Album:");
        albumText.setBorder(null);
        albumText.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(albumText, gridBagConstraints);

        titleText.setEditable(false);
        titleText.setText("Title:");
        titleText.setBorder(null);
        titleText.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(titleText, gridBagConstraints);

        yearText.setEditable(false);
        yearText.setText("Year:");
        yearText.setBorder(null);
        yearText.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(yearText, gridBagConstraints);

        genreText.setEditable(false);
        genreText.setText("Genre:");
        genreText.setBorder(null);
        genreText.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(genreText, gridBagConstraints);

        title.setEditable(false);
        title.setBorder(null);
        title.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(title, gridBagConstraints);

        fileNameText.setEditable(false);
        fileNameText.setText("Filename:");
        fileNameText.setBorder(null);
        fileNameText.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(fileNameText, gridBagConstraints);

        urlText.setEditable(false);
        urlText.setText("URL:");
        urlText.setBorder(null);
        urlText.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(urlText, gridBagConstraints);

        filename.setEditable(false);
        filename.setBorder(null);
        filename.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(filename, gridBagConstraints);

        encoder.setEditable(false);
        encoder.setBorder(null);
        encoder.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(encoder, gridBagConstraints);

        album.setEditable(false);
        album.setBorder(null);
        album.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(album, gridBagConstraints);

        artist.setEditable(false);
        artist.setBorder(null);
        artist.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(artist, gridBagConstraints);

        year.setEditable(false);
        year.setBorder(null);
        year.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(year, gridBagConstraints);

        genre.setEditable(false);
        genre.setBorder(null);
        genre.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(genre, gridBagConstraints);

        copyrightText.setEditable(false);
        copyrightText.setText("Copyright:");
        copyrightText.setBorder(null);
        copyrightText.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(copyrightText, gridBagConstraints);

        albumArtistText.setEditable(false);
        albumArtistText.setText("Album artist:");
        albumArtistText.setBorder(null);
        albumArtistText.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(albumArtistText, gridBagConstraints);

        originalArtistText.setEditable(false);
        originalArtistText.setText("Original artist:");
        originalArtistText.setBorder(null);
        originalArtistText.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(originalArtistText, gridBagConstraints);

        publisherText.setEditable(false);
        publisherText.setText("Publisher:");
        publisherText.setBorder(null);
        publisherText.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(publisherText, gridBagConstraints);

        encoderText.setEditable(false);
        encoderText.setText("Encoder:");
        encoderText.setBorder(null);
        encoderText.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(encoderText, gridBagConstraints);

        composerText6.setEditable(false);
        composerText6.setText("Composer:");
        composerText6.setBorder(null);
        composerText6.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(composerText6, gridBagConstraints);

        url.setEditable(false);
        url.setBorder(null);
        url.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(url, gridBagConstraints);

        copyright.setEditable(false);
        copyright.setBorder(null);
        copyright.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(copyright, gridBagConstraints);

        albumArtist.setEditable(false);
        albumArtist.setBorder(null);
        albumArtist.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(albumArtist, gridBagConstraints);

        oroginalArtist.setEditable(false);
        oroginalArtist.setBorder(null);
        oroginalArtist.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(oroginalArtist, gridBagConstraints);

        publisher.setEditable(false);
        publisher.setBorder(null);
        publisher.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(publisher, gridBagConstraints);

        composer.setEditable(false);
        composer.setBorder(null);
        composer.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(composer, gridBagConstraints);

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField album;
    private javax.swing.JTextField albumArtist;
    private javax.swing.JTextField albumArtistText;
    private javax.swing.JTextField albumText;
    private javax.swing.JTextField artist;
    private javax.swing.JTextField artistText;
    private javax.swing.JTextField composer;
    private javax.swing.JTextField composerText6;
    private javax.swing.JTextField copyright;
    private javax.swing.JTextField copyrightText;
    private javax.swing.JTextField encoder;
    private javax.swing.JTextField encoderText;
    private javax.swing.JTextField fileNameText;
    private javax.swing.JTextField filename;
    private javax.swing.JTextField genre;
    private javax.swing.JTextField genreText;
    private javax.swing.JTextField originalArtistText;
    private javax.swing.JTextField oroginalArtist;
    private javax.swing.JTextField publisher;
    private javax.swing.JTextField publisherText;
    private javax.swing.JTextField title;
    private javax.swing.JTextField titleText;
    private javax.swing.JTextField url;
    private javax.swing.JTextField urlText;
    private javax.swing.JTextField year;
    private javax.swing.JTextField yearText;
    // End of variables declaration//GEN-END:variables
}
